"""add cascade delete constraints

Revision ID: 0d60dd2967d2
Revises: fcf88b4d7606
Create Date: 2026-06-21 02:15:29.490962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d60dd2967d2'
down_revision: Union[str, None] = 'fcf88b4d7606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('chat_history_user_id_fkey', 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('courses_instructor_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'users', ['instructor_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('reviews_trip_id_fkey', 'reviews', type_='foreignkey')
    op.drop_constraint('reviews_user_id_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'trips', ['trip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_user_id_fkey', 'reviews', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('reviews_trip_id_fkey', 'reviews', 'trips', ['trip_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reviews', 'trip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_instructor_id_fkey', 'courses', 'users', ['instructor_id'], ['id'])
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key('chat_history_user_id_fkey', 'chat_history', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('chat_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
