"""add auto data  to booking

Revision ID: d2db1d95919a
Revises: 0a8b4c2e997e
Create Date: 2026-06-21 15:01:07.092898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2db1d95919a'
down_revision: Union[str, None] = '0a8b4c2e997e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
